-- Instrucción SQL para crear la tabla 'users' en Supabase
-- Ejecuta este script en el editor SQL de tu panel de Supabase.

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- O BIGINT GENERATED BY DEFAULT AS IDENTITY
    firebase_uid TEXT UNIQUE NOT NULL,             -- El UID proveniente de Firebase
    email TEXT NULL,                               -- Email del usuario (puede ser nulo si es anónimo)
    display_name TEXT NULL,                        -- Nombre a mostrar
    photo_url TEXT NULL,                           -- Enlace de foto de perfil
    created_at TIMESTAMP WITH TIMEZONE DEFAULT NOW() NOT NULL,
    is_anonymous BOOLEAN DEFAULT FALSE NOT NULL    -- Indica si la cuenta es anónima
);

-- Habilitar Row Level Security (RLS) si se desea proteger la tabla
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Crear políticas básicas para permitir lecturas y upserts públicos/autenticados
CREATE POLICY "Permitir lecturas públicas de usuarios" 
ON public.users FOR SELECT 
USING (true);

CREATE POLICY "Permitir inserciones y actualizaciones públicas" 
ON public.users FOR ALL 
USING (true) 
WITH CHECK (true);
