-- ==============================================================================
-- 🔔 TABLA DE SUSCRIPCIONES A NOTIFICACIONES DE PERFILES DE ESTUDIANTES
-- ==============================================================================
-- Ejecuta este script en el SQL Editor de tu panel de Supabase:
-- https://supabase.com/dashboard/project/_/sql

CREATE TABLE IF NOT EXISTS public.student_notification_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    user_uid TEXT NOT NULL,
    notify_crush BOOLEAN DEFAULT true NOT NULL,
    notify_love_message BOOLEAN DEFAULT true NOT NULL,
    notify_known BOOLEAN DEFAULT true NOT NULL,
    notify_fan BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(student_id, user_uid)
);

-- Índices de búsqueda para máximo rendimiento
CREATE INDEX IF NOT EXISTS idx_student_notif_sub_student ON public.student_notification_subscriptions(student_id);
CREATE INDEX IF NOT EXISTS idx_student_notif_sub_user ON public.student_notification_subscriptions(user_uid);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.student_notification_subscriptions ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad RLS
CREATE POLICY "Lectura de suscripciones" 
    ON public.student_notification_subscriptions FOR SELECT 
    USING (true);

CREATE POLICY "Inserción y actualización de suscripciones" 
    ON public.student_notification_subscriptions FOR ALL 
    USING (true)
    WITH CHECK (true);
