-- ==============================================================================
-- 🔔 TABLA DE SUSCRIPCIONES A NOTIFICACIONES DE PERFILES DE PROFESORES
-- ==============================================================================
-- Ejecuta este script en el SQL Editor de tu panel de Supabase:
-- https://supabase.com/dashboard/project/_/sql

CREATE TABLE IF NOT EXISTS public.professor_notification_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id TEXT NOT NULL,
    user_uid TEXT NOT NULL,
    notify_crush BOOLEAN DEFAULT true NOT NULL,
    notify_review BOOLEAN DEFAULT true NOT NULL,
    notify_known BOOLEAN DEFAULT true NOT NULL,
    notify_fan BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(professor_id, user_uid)
);

-- Índices de búsqueda para máximo rendimiento
CREATE INDEX IF NOT EXISTS idx_prof_notif_sub_prof ON public.professor_notification_subscriptions(professor_id);
CREATE INDEX IF NOT EXISTS idx_prof_notif_sub_user ON public.professor_notification_subscriptions(user_uid);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.professor_notification_subscriptions ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad RLS
CREATE POLICY "Lectura de suscripciones de profesores" 
    ON public.professor_notification_subscriptions FOR SELECT 
    USING (true);

CREATE POLICY "Inserción y actualización de suscripciones de profesores" 
    ON public.professor_notification_subscriptions FOR ALL 
    USING (true)
    WITH CHECK (true);
