-- ============================================================================
-- SCRIPT DE MIGRACIÓN: ECOSISTEMA COMPLETO DE USUARIOS EN SUPABASE
-- Crea las tablas: users_votes, users_love_messages, users_love_message_hearts, users_daily_stats
-- Ejecuta este script en el SQL Editor de tu Dashboard de Supabase.
-- ============================================================================

-- 1. TABLA 'users_votes' (Calificaciones de 1 a 5 estrellas para perfiles de usuario)
CREATE TABLE IF NOT EXISTS public.users_votes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  target_user_id TEXT NOT NULL,       -- ID del usuario que recibe el voto
  user_uid TEXT NOT NULL,             -- ID del usuario que vota
  stars SMALLINT NOT NULL CHECK (stars >= 1 AND stars <= 5),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_votes_target ON public.users_votes(target_user_id);
CREATE INDEX IF NOT EXISTS idx_users_votes_voter ON public.users_votes(user_uid, target_user_id);

ALTER TABLE public.users_votes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura pública de users_votes" ON public.users_votes;
CREATE POLICY "Lectura pública de users_votes"
  ON public.users_votes FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Inserción de users_votes" ON public.users_votes;
CREATE POLICY "Inserción de users_votes"
  ON public.users_votes FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Eliminación de users_votes" ON public.users_votes;
CREATE POLICY "Eliminación de users_votes"
  ON public.users_votes FOR DELETE
  USING (true);


-- 2. TABLA 'users_love_messages' (Mensajes de amor / confesiones hacia perfiles de usuario)
CREATE TABLE IF NOT EXISTS public.users_love_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id TEXT NOT NULL,       -- ID del usuario receptor
  user_uid TEXT NOT NULL,             -- ID del autor del mensaje
  author_name TEXT NOT NULL DEFAULT 'Anónimo',
  author_avatar TEXT,
  author_gender TEXT,
  content TEXT NOT NULL,
  hearts_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_love_messages_target ON public.users_love_messages(target_user_id);

ALTER TABLE public.users_love_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura pública de users_love_messages" ON public.users_love_messages;
CREATE POLICY "Lectura pública de users_love_messages"
  ON public.users_love_messages FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Inserción de users_love_messages" ON public.users_love_messages;
CREATE POLICY "Inserción de users_love_messages"
  ON public.users_love_messages FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Actualización de users_love_messages" ON public.users_love_messages;
CREATE POLICY "Actualización de users_love_messages"
  ON public.users_love_messages FOR UPDATE
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Eliminación de users_love_messages" ON public.users_love_messages;
CREATE POLICY "Eliminación de users_love_messages"
  ON public.users_love_messages FOR DELETE
  USING (true);


-- 3. TABLA 'users_love_message_hearts' (Corazones a mensajes de amor de usuarios)
CREATE TABLE IF NOT EXISTS public.users_love_message_hearts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  message_id BIGINT NOT NULL,
  user_uid TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT unique_users_love_msg_heart UNIQUE (message_id, user_uid)
);

CREATE INDEX IF NOT EXISTS idx_users_love_msg_hearts_lookup ON public.users_love_message_hearts(message_id, user_uid);

ALTER TABLE public.users_love_message_hearts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura pública de users_love_message_hearts" ON public.users_love_message_hearts;
CREATE POLICY "Lectura pública de users_love_message_hearts"
  ON public.users_love_message_hearts FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Inserción de users_love_message_hearts" ON public.users_love_message_hearts;
CREATE POLICY "Inserción de users_love_message_hearts"
  ON public.users_love_message_hearts FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Eliminación de users_love_message_hearts" ON public.users_love_message_hearts;
CREATE POLICY "Eliminación de users_love_message_hearts"
  ON public.users_love_message_hearts FOR DELETE
  USING (true);


-- 4. TABLA 'users_daily_stats' (Histórico diario de estadísticas de usuarios)
CREATE TABLE IF NOT EXISTS public.users_daily_stats (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  target_user_id TEXT NOT NULL,
  date DATE NOT NULL,
  knows_count INTEGER NOT NULL DEFAULT 0,
  fans_count INTEGER NOT NULL DEFAULT 0,
  crushes_count INTEGER NOT NULL DEFAULT 0,
  score NUMERIC(3, 2) NOT NULL DEFAULT 0.0,
  views_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT unique_user_daily_stat UNIQUE (target_user_id, date)
);

CREATE INDEX IF NOT EXISTS idx_users_daily_stats_lookup ON public.users_daily_stats(target_user_id, date DESC);

ALTER TABLE public.users_daily_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura pública de users_daily_stats" ON public.users_daily_stats;
CREATE POLICY "Lectura pública de users_daily_stats"
  ON public.users_daily_stats FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Inserción de users_daily_stats" ON public.users_daily_stats;
CREATE POLICY "Inserción de users_daily_stats"
  ON public.users_daily_stats FOR ALL
  USING (true)
  WITH CHECK (true);
